/* Escola Noturna — o currículo: blocos e aulas da grade */
/* ---------- Currículo (conteúdo da grade) ---------- */
const BLOCOS = {
  1:{nome:'Bloco 1 · A física do .NET', quando:'out–dez/2026'},
  2:{nome:'Bloco 2 · Arquitetura e qualidade', quando:'jan–mar/2027'},
  3:{nome:'Bloco 3 · Dados em escala', quando:'abr–jun/2027'},
  C:{nome:'Comunicação e liderança', quando:'out/2026–abr/2027'}
};
// id, trilha, bloco, módulo, título, decisão/técnica, laboratório/prática, semana planejada
const RAW = [
 ['T1','T',1,'Runtime','Memória: stack, heap, class x struct, boxing, records','class ou struct? record ou record struct?','Medir alocações com BenchmarkDotNet',1],
 ['T2','T',1,'Runtime','Garbage Collector: gerações, heap de objetos grandes, GC de servidor x estação','Por que a API engasga de tempos em tempos?','Ver o GC ao vivo com dotnet-counters',1],
 ['T3','T',1,'Runtime','JIT, compilação em camadas, PGO dinâmico, Native AOT','Vale compilar AOT? Por que o primeiro request é lento?','Comparar partida JIT x AOT',2],
 ['T4','T',1,'Runtime','Span, Memory, ArrayPool, stackalloc','Como ler 2 GB sem criar lixo?','Exercício-ponte v2: parser sem strings',2],
 ['T5','T',1,'Runtime','Coleções por dentro: List, Dictionary, HashSet, FrozenDictionary, PriorityQueue','Qual coleção para esse padrão de acesso?','Exercício-ponte v3: array + heap',3],
 ['T6','T',1,'Runtime','Medir de verdade: benchmark, ruído, profiling, flame graph','Otimizo ou não? Onde o tempo está indo?','dotnet-trace e flame graph da v3',3],
 ['P1','T',1,'Runtime','Prova 1: o que cada mudança comprou','Você mede antes de opinar','Tabela v1→v3 com o mecanismo de cada ganho',4],
 ['T7','T',1,'Concorrência','Threads, ThreadPool, CPU x I/O, Lei de Amdahl','Quantos núcleos ajudam de verdade?','Calcular o teto teórico do paralelo',4],
 ['T8','T',1,'Concorrência','async/await por dentro: máquina de estados, contexto, ValueTask, deadlocks','async aqui ajuda ou atrapalha?','Reproduzir e corrigir um deadlock com .Result',5],
 ['T9','T',1,'Concorrência','Parallel.For, PLINQ, particionamento, estado por thread, false sharing','Como dividir o trabalho sem as threads brigarem?','Exercício-ponte v4: paralelo',5],
 ['T10','T',1,'Concorrência','Channels e Pipelines: produtor/consumidor, contrapressão','Como importar arquivos sem estourar a memória?','Pipeline de ingestão com Channel',6],
 ['T11','T',1,'Concorrência','Sincronização: lock, Interlocked, ConcurrentDictionary, condições de corrida','Onde está a corrida neste código?','Caçar 3 bugs de concorrência plantados',6],
 ['P2','T',1,'Concorrência','Prova 2: vale paralelizar?','Você sabe quando não otimizar','Versão paralela medida + ADR',7],
 ['T12','T',1,'Banco de dados','Como o banco acha dados: páginas, árvore B, índice clusterizado e de cobertura, seek x scan','Esse índice ajuda ou só pesa na escrita?','Ler um plano de execução',7],
 ['T13','T',1,'Banco de dados','SQL que escala: sargabilidade, algoritmos de join, estatísticas, parameter sniffing','Por que a query ficou lenta do nada?','Quebrar e consertar uma query',8],
 ['T14','T',1,'Banco de dados','EF Core por dentro: change tracking, AsNoTracking, N+1, split query, projeções, ExecuteUpdate','Esse LINQ vira qual SQL, e quantas idas ao banco?','Logar o SQL gerado e cortar consultas',8],
 ['T15','T',1,'Banco de dados','EF Core x Dapper x SQL puro; inserção em massa','Qual ferramenta para cada caso?','Inserir 1 milhão de linhas de 3 jeitos',9],
 ['T16','T',1,'Banco de dados','Transações e isolamento: anomalias, concorrência otimista','Dois usuários editam ao mesmo tempo: quem ganha?','Simular a perda de uma atualização',9],
 ['T17','T',1,'Banco de dados','Modelagem analítica: OLTP x OLAP, estrela, grão, dimensão que muda, columnstore','Como modelar a venda para o painel?','Modelar o dataset do teste em estrela',10],
 ['T18','T',1,'Banco de dados','Pré-agregação: rollups incrementais, dado atrasado, marca d\'água','Somar na hora do clique ou antes?','Rollup diário incremental',10],
 ['P3','T',1,'Banco de dados','Prova 3: palestra "36 milhões de linhas em .NET"','Você ensina o time','Palestra interna de 15 minutos',11],
 ['T19','T',2,'Arquitetura e qualidade','MediatR e CQRS: o que dá, o que custa, pipeline behaviors','Esse handler precisa existir ou é só cerimônia?','Behavior de validação e log',14],
 ['T20','T',2,'Arquitetura e qualidade','Design: coesão, acoplamento, a classe que faz tudo, SOLID sem dogma, objetos de valor','Onde essa regra de negócio deveria morar?','Refatorar a "classe que faz tudo" apontada pela Coderockr',15],
 ['T21','T',2,'Arquitetura e qualidade','Testes como arquitetura: os 4 pilares do Khorikov, o que mockar, Testcontainers','Esse teste protege ou só atrapalha a mudança?','Teste de integração com banco real num container',17],
 ['T22','T',2,'Arquitetura e qualidade','Erros e resiliência: exceção x Result, retry, timeout, circuit breaker','Tentar de novo é seguro aqui?','Resiliência HTTP com Microsoft.Extensions.Http.Resilience',18],
 ['T23','T',2,'Arquitetura e qualidade','Observabilidade: logs estruturados, métricas, tracing com OpenTelemetry','Como saber o que aconteceu sem adivinhar?','Rastrear um request de ponta a ponta',20],
 ['T24','T',2,'Arquitetura e qualidade','ASP.NET Core e Kestrel: middleware, DI e tempos de vida, rate limiting, cache','Por que esse serviço vaza estado entre requests?','Achar um bug de tempo de vida (captive dependency)',21],
 ['T25','T',2,'Arquitetura e qualidade','Blazor: modos de renderização (Server, WebAssembly, Auto) e Blazor x Vue','Essa tela vai em Blazor ou Vue?','A mesma tela em dois modos, medindo',23],
 ['P4','T',2,'Arquitetura e qualidade','Prova 4: primeiro ADR real na Varejo','Você decide com critério','ADR revisado pelo Kauã',25],
 ['T26','T',3,'Dados em escala','Ingestão de arquivos de ERPs: contrato de formato, evolução, quarentena, idempotência por hash','O que fazer com a linha que não bate?','Importador com quarentena',27],
 ['T27','T',3,'Dados em escala','Filas e mensagens: "pelo menos uma vez", a ilusão do "exatamente uma vez", outbox','E se o servidor cair no meio da gravação?','Outbox com EF Core',28],
 ['T28','T',3,'Dados em escala','Multi-cliente: banco compartilhado x esquema x banco por cliente, filtros globais, RLS','Como garantir que a loja A nunca veja a loja B?','Teste automático de isolamento',30],
 ['T29','T',3,'Dados em escala','Privacidade em dado coletivo: LGPD, anonimização, k-anonimato, agregação mínima','Posso mostrar esse benchmark sem expor ninguém?','Regra que esconde grupos pequenos demais',31],
 ['T30','T',3,'Dados em escala','Estimativa de guardanapo: latência, capacidade, custo de nuvem','Aguenta 10 vezes mais clientes? Quanto custa?','Dimensionar a Varejo com 1.000 lojas',33],
 ['T31','T',3,'Dados em escala','IA no produto: previsão de demanda, linha de base sazonal, medir o erro','Precisa de modelo de ML ou de uma média bem feita?','Linha de base de previsão com os dados do teste',34],
 ['T32','T',3,'Dados em escala','Design de sistema: projetar o VC Entende do zero','Integra tudo','Documento de design + 3 ADRs',36],
 ['P5','T',3,'Dados em escala','Prova 5: defender o design do VC Entende','Você pensa no sistema inteiro','Apresentar ao Kauã e defender as escolhas',38],
 ['C1','C','C','A · Por que a comunicação funciona','Por que a gente trava: memória de trabalho e nervosismo','Estruturas prontas liberam a cabeça','Gravar 3 respostas com os formatos do Pilar 3',1],
 ['C2','C','C','A · Por que a comunicação funciona','Princípio da Pirâmide (Barbara Minto) e SCQA','Conclusão primeiro, argumentos agrupados embaixo','Reescrever um e-mail e uma fala sua',2],
 ['C3','C','C','A · Por que a comunicação funciona','Retórica de Aristóteles: ethos, pathos, logos','Propor uma decisão técnica que convence','Gravar a proposta do exercício-ponte em 2 min',3],
 ['C4','C','C','A · Por que a comunicação funciona','Maldição do conhecimento e escada da abstração (Made to Stick)','Explicar técnico para quem não é técnico','Explicar índice de banco para o Gustavo em 90 s',4],
 ['C5','C','C','A · Por que a comunicação funciona','Escuta ativa (Carl Rogers)','Parafrasear, perguntar, confirmar','Usar em 3 conversas reais e anotar',5],
 ['C6','C','C','A · Por que a comunicação funciona','Voz e improviso: ritmo, pausa, ênfase; PREP','Responder bem sem ter preparado','5 perguntas-surpresa, 60 s cada',6],
 ['C7','C','C','B · Comunicação de engenharia','Escrita técnica: design docs, ADRs, memorando de 6 páginas','PR, ADR e status que se leem em 1 minuto','Reescrever a descrição de um PR real',7],
 ['C8','C','C','B · Comunicação de engenharia','Dinâmica de reuniões e turnos de fala','Onde e como entrar na conversa, no remoto','Falar em todas as reuniões da semana',8],
 ['C9','C','C','B · Comunicação de engenharia','Decisão sob trade-offs: tabela de opções e recomendação','Apresentar uma decisão e aguentar as perguntas','Apresentar a Prova 2 gravada, 5 min',9],
 ['C10','C','C','B · Comunicação de engenharia','Narrativa: STAR e o documento de conquistas','Suas 5 histórias, prontas','Gravar as 5 histórias',10],
 ['C11','C','C','C · Liderança e gestão','Feedback: modelo SBI e Radical Candor','Dar e pedir feedback sem drama','Pedir feedback ao Kauã no 1:1',11],
 ['C12','C','C','C · Liderança e gestão','Conversas difíceis: Crucial Conversations e CNV (Rosenberg)','Discordar de alguém mais sênior','Roteiro de uma discordância real',14],
 ['C13','C','C','C · Liderança e gestão','Negociação: interesses x posições, BATNA (Getting to Yes)','Preparar uma negociação','Preparar a conversa de revisão de valor e escopo',17],
 ['C14','C','C','C · Liderança e gestão','Confiança e influência sem cargo: Maister, Cialdini com ética','Ganhar apoio para uma ideia','Mapear quem precisa concordar com sua próxima proposta',19],
 ['C15','C','C','C · Liderança e gestão','Gestão: 1:1s, delegação e níveis de autonomia','Delegar sem largar','Plano de onboarding para o próximo dev',21],
 ['C16','C','C','C · Liderança e gestão','Decisão em grupo e segurança psicológica (Amy Edmondson)','Facilitar uma decisão de time','Conduzir uma discussão técnica curta',23],
 ['C17','C','C','C · Liderança e gestão','Culturas: Brasil x Áustria (The Culture Map)','Feedback direto, contexto explícito, pontualidade','Reescrever 3 mensagens no "modo austríaco"',27],
 ['C18','C','C','C · Liderança e gestão','Prova final: apresentação de 10 min + perguntas','Conclusão no primeiro minuto, sem travar','Avaliada por rubrica',29]
];
const CAT = RAW.map(r=>({id:r[0],trilha:r[1],bloco:r[2],modulo:r[3],titulo:r[4],decisao:r[5],lab:r[6],sem:r[7],prova:r[0][0]==='P'||r[0]==='C18'}));
const BYID = Object.fromEntries(CAT.map(l=>[l.id,l]));
